name: Generator CI
on: [push, pull_request]
jobs:
  generator-jhipster-nodejs:
   name: npm test
   runs-on: ${{ matrix.os }}
   if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
   timeout-minutes: 20
   strategy:
     fail-fast: false
     matrix:
       node_version: [12.14.0]
       os: [ubuntu-latest]
   steps:
    - uses: actions/checkout@v1
#    - uses: SonarSource/sonarcloud-github-action@v1.1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}   
    - name: git history
      run: git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) <%an>%Creset' --abbrev-commit  
    - run: npm ci
    - run: npm test
    - name: 'Sonar analysis'
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
